version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
#      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - network.host=0.0.0.0
    volumes:
      - 'elasticsearch_data:/usr/share/elasticsearch/data'
    ports:
      - '9200:9200'
      - '9300:9300'
volumes:
  elasticsearch_data:
    driver: local