###
GET http://localhost:9200/archive/_search?q=doc*
Authorization: Basic ZWxhc3RpYzpjaGFuZ2VtZQ==

###
GET http://localhost:9200/archive/_search?q=NÆRINGSSTOFFER
Authorization: Basic ZWxhc3RpYzpjaGFuZ2VtZQ==

###
GET http://localhost:9200/_cat/indices?v
Authorization: Basic ZWxhc3RpYzpjaGFuZ2VtZQ==

###
DELETE http://localhost:9200/archive
Authorization: Basic ZWxhc3RpYzpjaGFuZ2VtZQ==